/**
 * 规则引擎（Rule Engine）
 * 负责加载、排序、格式化规则并注入到 systemPrompt
 */

import { RuleDao } from '../db/dao.js';
import type { ProjectRule, RuleCategory } from '../types/rules.js';
import { getRulePriority } from '../types/rules.js';

const RULE_CATEGORY_CONFIG: Record<RuleCategory, { label: string; xmlTag: string; section: 'static' | 'dynamic' | 'memory' }> = {
  code_style:        { label: '编码规范', xmlTag: 'code-style', section: 'static' },
  constraints:       { label: '约束条件', xmlTag: 'constraints', section: 'static' },
  domain_knowledge:  { label: '领域知识', xmlTag: 'domain-knowledge', section: 'static' },
  best_practices:    { label: '最佳实践', xmlTag: 'best-practices', section: 'static' },
  completed_items:   { label: '已完成事项', xmlTag: 'completed-items', section: 'dynamic' },
  current_progress:  { label: '当前进展', xmlTag: 'current-progress', section: 'dynamic' },
  decisions:         { label: '关键决策', xmlTag: 'decisions', section: 'dynamic' },
  blockers:          { label: '当前阻塞', xmlTag: 'blockers', section: 'dynamic' },
  session_summaries: { label: '会话摘要', xmlTag: 'session-summaries', section: 'memory' },
  key_learnings:     { label: '关键经验', xmlTag: 'key-learnings', section: 'memory' },
};

export interface RuleEngineOptions {
  maxRules?: number;
  includeAutoGenerated?: boolean;
}

export interface RuleSystemPrompt {
  rulesXml: string;
  rulesByCategory: Partial<Record<RuleCategory, ProjectRule[]>>;
  stats: {
    totalRules: number;
    staticCount: number;
    dynamicCount: number;
    memoryCount: number;
    categories: RuleCategory[];
  };
}

export class RuleEngine {
  private options: Required<RuleEngineOptions>;

  constructor(options: RuleEngineOptions = {}) {
    this.options = {
      maxRules: options.maxRules ?? 50,
      includeAutoGenerated: options.includeAutoGenerated ?? true,
    };
  }

  async getRules(projectId: string): Promise<ProjectRule[]> {
    const allRules = RuleDao.findByProject(projectId);
    const filteredRules = this.options.includeAutoGenerated
      ? allRules
      : allRules.filter(r => !r.autoGenerated);
    return filteredRules.sort((a, b) => {
      if (b.priority !== a.priority) return b.priority - a.priority;
      return b.updatedAt - a.updatedAt;
    });
  }

  private groupRulesByCategory(rules: ProjectRule[]): Partial<Record<RuleCategory, ProjectRule[]>> {
    const grouped: Partial<Record<RuleCategory, ProjectRule[]>> = {};
    for (const rule of rules) {
      const cat = rule.category as RuleCategory;
      if (!grouped[cat]) grouped[cat] = [];
      grouped[cat]!.push(rule);
    }
    return grouped;
  }

  private escapeXml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
  }

  private formatRuleAsXml(rule: ProjectRule): string {
    const config = RULE_CATEGORY_CONFIG[rule.category as RuleCategory];
    if (!config) return `<rule category="${rule.category}" priority="${rule.priority}">${this.escapeXml(rule.content)}</rule>`;
    const autoAttr = rule.autoGenerated ? ' auto-generated="true"' : '';
    return `<${config.xmlTag} priority="${rule.priority}"${autoAttr}>${this.escapeXml(rule.content)}</${config.xmlTag}>`;
  }

  private generateRulesXml(rules: ProjectRule[]): string {
    const sections: string[] = [];
    const staticRules = rules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'static');
    const dynamicRules = rules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'dynamic');
    const memoryRules = rules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'memory');
    if (staticRules.length > 0) sections.push(`  <static-rules>${staticRules.map(r => this.formatRuleAsXml(r)).join(' ')}</static-rules>`);
    if (dynamicRules.length > 0) sections.push(`  <dynamic-rules>${dynamicRules.map(r => this.formatRuleAsXml(r)).join(' ')}</dynamic-rules>`);
    if (memoryRules.length > 0) sections.push(`  <memory>${memoryRules.map(r => this.formatRuleAsXml(r)).join(' ')}</memory>`);
    return `<rules>${sections.join(' ')}</rules>`;
  }

  async getSystemPromptFragment(projectId: string): Promise<RuleSystemPrompt> {
    const rules = await this.getRules(projectId);
    const limitedRules = rules.slice(0, this.options.maxRules);
    const rulesByCategory = this.groupRulesByCategory(limitedRules);
    const rulesXml = this.generateRulesXml(limitedRules);
    const staticCount = limitedRules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'static').length;
    const dynamicCount = limitedRules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'dynamic').length;
    const memoryCount = limitedRules.filter(r => RULE_CATEGORY_CONFIG[r.category as RuleCategory]?.section === 'memory').length;
    return {
      rulesXml,
      rulesByCategory,
      stats: { totalRules: limitedRules.length, staticCount, dynamicCount, memoryCount, categories: [...new Set(limitedRules.map(r => r.category as RuleCategory))] },
    };
  }

  async mergeWithBasePrompt(basePrompt: string, projectId: string): Promise<string> {
    const fragment = await this.getSystemPromptFragment(projectId);
    if (fragment.stats.totalRules === 0) return basePrompt;
    return `${basePrompt}\n\n---\n\n## Project Rules & Memory\n\n${fragment.rulesXml}\n\n---\n\nInstructions:\n- Follow all rules in the <rules> section above\n- Static rules are always active and must be followed\n- Dynamic rules reflect current project state and should be considered\n- Memory entries provide historical context for decision-making`;
  }

  async createRule(projectId: string, category: RuleCategory, content: string, priority?: number, autoGenerated?: boolean): Promise<ProjectRule> {
    return RuleDao.create({ projectId, category, content, priority: priority ?? getRulePriority(category), autoGenerated: autoGenerated ?? false });
  }

  async updateRule(ruleId: string, content?: string, priority?: number): Promise<ProjectRule | null> {
    const updates: Partial<Pick<ProjectRule, 'content' | 'priority'>> = {};
    if (content !== undefined) updates.content = content;
    if (priority !== undefined) updates.priority = priority;
    return RuleDao.update(ruleId, updates);
  }

  async deleteRule(ruleId: string): Promise<boolean> { return RuleDao.delete(ruleId); }
  async deleteRulesByProject(projectId: string): Promise<void> { RuleDao.deleteByProject(projectId); }
}

export function createRuleEngine(options: RuleEngineOptions = {}): RuleEngine {
  return new RuleEngine(options);
}
