/**
 * 数据库操作 DAO
 */

import { getDatabaseManager } from "./connection.js";
import { Project, ProjectRule, Session, SessionMessage, MemoryEntry } from "../types/rules.js";
import { v4 as uuidv4 } from "uuid";

const db = getDatabaseManager();

// ============================================================================
// Project DAO
// ============================================================================

const insertProject = db.prepare(`
  INSERT INTO projects (id, name, description, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?)
`);

const selectProjectById = db.prepare(`
  SELECT * FROM projects WHERE id = ?
`);

const selectAllProjects = db.prepare(`
  SELECT * FROM projects ORDER BY created_at DESC
`);

const updateProject = db.prepare(`
  UPDATE projects SET name = ?, description = ?, updated_at = ? WHERE id = ?
`);

const deleteProject = db.prepare(`
  DELETE FROM projects WHERE id = ?
`);

export const ProjectDao = {
  create(project: Omit<Project, "id" | "createdAt" | "updatedAt">): Project {
    const id = uuidv4();
    const now = Date.now();
    insertProject.run(id, project.name, project.description || null, now, now);
    return { ...project, id, createdAt: now, updatedAt: now };
  },

  findById(id: string): Project | null {
    return selectProjectById.get(id) as Project | null;
  },

  findAll(): Project[] {
    return selectAllProjects.all() as Project[];
  },

  update(id: string, data: Partial<Pick<Project, "name" | "description">>): Project | null {
    const now = Date.now();
    const project = this.findById(id);
    if (!project) return null;
    updateProject.run(data.name ?? project.name, data.description ?? project.description, now, id);
    return { ...project, ...data, updatedAt: now };
  },

  delete(id: string): boolean {
    const result = deleteProject.run(id);
    return result.changes > 0;
  },
};

// ============================================================================
// ProjectRule DAO
// ============================================================================

const insertRule = db.prepare(`
  INSERT INTO project_rules (id, project_id, category, content, priority, auto_generated, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`);

const selectRulesByProject = db.prepare(`
  SELECT * FROM project_rules WHERE project_id = ? ORDER BY priority DESC, created_at DESC
`);

const selectRulesByCategory = db.prepare(`
  SELECT * FROM project_rules WHERE project_id = ? AND category = ? ORDER BY priority DESC
`);

const updateRule = db.prepare(`
  UPDATE project_rules SET content = ?, priority = ?, updated_at = ? WHERE id = ?
`);

const deleteRule = db.prepare(`
  DELETE FROM project_rules WHERE id = ?
`);

const deleteRulesByProject = db.prepare(`
  DELETE FROM project_rules WHERE project_id = ?
`);

export const RuleDao = {
  create(rule: Omit<ProjectRule, "id" | "createdAt" | "updatedAt">): ProjectRule {
    const id = uuidv4();
    const now = Date.now();
    insertRule.run(
      id, rule.projectId, rule.category, rule.content,
      rule.priority ?? 0, rule.autoGenerated ?? false, now, now
    );
    return { ...rule, id, createdAt: now, updatedAt: now };
  },

  findByProject(projectId: string): ProjectRule[] {
    return selectRulesByProject.all(projectId) as ProjectRule[];
  },

  findByCategory(projectId: string, category: string): ProjectRule[] {
    return selectRulesByCategory.all(projectId, category) as ProjectRule[];
  },

  update(id: string, data: Partial<Pick<ProjectRule, "content" | "priority">>): ProjectRule | null {
    const rule = this.findById(id);
    if (!rule) return null;
    const now = Date.now();
    updateRule.run(data.content ?? rule.content, data.priority ?? rule.priority, now, id);
    return { ...rule, ...data, updatedAt: now };
  },

  findById(id: string): ProjectRule | null {
    const result = db.prepare("SELECT * FROM project_rules WHERE id = ?").get(id);
    return result as ProjectRule | null;
  },

  delete(id: string): boolean {
    const result = deleteRule.run(id);
    return result.changes > 0;
  },

  deleteByProject(projectId: string): void {
    deleteRulesByProject.run(projectId);
  },
};

// ============================================================================
// Session DAO
// ============================================================================

const insertSession = db.prepare(`
  INSERT INTO sessions (id, project_id, title, created_at, updated_at)
  VALUES (?, ?, ?, ?, ?)
`);

const selectSessionById = db.prepare(`
  SELECT * FROM sessions WHERE id = ?
`);

const selectSessionsByProject = db.prepare(`
  SELECT * FROM sessions WHERE project_id = ? ORDER BY updated_at DESC
`);

const updateSession = db.prepare(`
  UPDATE sessions SET title = ?, updated_at = ? WHERE id = ?
`);

const deleteSession = db.prepare(`
  DELETE FROM sessions WHERE id = ?
`);

export const SessionDao = {
  create(session: Omit<Session, "id" | "createdAt" | "updatedAt">): Session {
    const id = uuidv4();
    const now = Date.now();
    insertSession.run(id, session.projectId, session.title || null, now, now);
    return { ...session, id, createdAt: now, updatedAt: now };
  },

  findById(id: string): Session | null {
    return selectSessionById.get(id) as Session | null;
  },

  findByProject(projectId: string): Session[] {
    return selectSessionsByProject.all(projectId) as Session[];
  },

  update(id: string, data: Partial<Pick<Session, "title">>): Session | null {
    const session = this.findById(id);
    if (!session) return null;
    const now = Date.now();
    updateSession.run(data.title ?? session.title, now, id);
    return { ...session, ...data, updatedAt: now };
  },

  delete(id: string): boolean {
    const result = deleteSession.run(id);
    return result.changes > 0;
  },
};

// ============================================================================
// SessionMessage DAO
// ============================================================================

const insertMessage = db.prepare(`
  INSERT INTO session_messages (id, session_id, role, content, metadata, created_at)
  VALUES (?, ?, ?, ?, ?, ?)
`);

const selectMessagesBySession = db.prepare(`
  SELECT * FROM session_messages WHERE session_id = ? ORDER BY created_at ASC
`);

const deleteMessagesBySession = db.prepare(`
  DELETE FROM session_messages WHERE session_id = ?
`);

export const MessageDao = {
  create(message: Omit<SessionMessage, "id" | "createdAt">): SessionMessage {
    const id = uuidv4();
    const now = Date.now();
    insertMessage.run(id, message.sessionId, message.role, message.content, message.metadata || null, now);
    return { ...message, id, createdAt: now };
  },

  findBySession(sessionId: string): SessionMessage[] {
    return selectMessagesBySession.all(sessionId) as SessionMessage[];
  },

  deleteBySession(sessionId: string): void {
    deleteMessagesBySession.run(sessionId);
  },
};

// ============================================================================
// MemoryEntry DAO
// ============================================================================

const insertMemory = db.prepare(`
  INSERT INTO memory_entries (id, project_id, category, summary, source_session_id, created_at)
  VALUES (?, ?, ?, ?, ?, ?)
`);

const selectMemoryByProject = db.prepare(`
  SELECT * FROM memory_entries WHERE project_id = ? ORDER BY created_at DESC
`);

const selectMemoryByCategory = db.prepare(`
  SELECT * FROM memory_entries WHERE project_id = ? AND category = ? ORDER BY created_at DESC
`);

const deleteMemoryByProject = db.prepare(`
  DELETE FROM memory_entries WHERE project_id = ?
`);

export const MemoryDao = {
  create(entry: Omit<MemoryEntry, "id" | "createdAt">): MemoryEntry {
    const id = uuidv4();
    const now = Date.now();
    insertMemory.run(id, entry.projectId, entry.category, entry.summary, entry.sourceSessionId || null, now);
    return { ...entry, id, createdAt: now };
  },

  findByProject(projectId: string): MemoryEntry[] {
    return selectMemoryByProject.all(projectId) as MemoryEntry[];
  },

  findByCategory(projectId: string, category: string): MemoryEntry[] {
    return selectMemoryByCategory.all(projectId, category) as MemoryEntry[];
  },

  deleteByProject(projectId: string): void {
    deleteMemoryByProject.run(projectId);
  },
};
