/**
 * 规则引擎数据模型
 */

import { Static, Type } from '@sinclair/typebox';

// ============================================================================
// 规则分类
// ============================================================================

export type RuleCategory =
  | 'code_style'
  | 'constraints'
  | 'domain_knowledge'
  | 'best_practices'
  | 'completed_items'
  | 'current_progress'
  | 'decisions'
  | 'blockers'
  | 'session_summaries'
  | 'key_learnings';

// ============================================================================
// 项目规则
// ============================================================================

export const ProjectRuleSchema = Type.Object({
  id: Type.String(),
  projectId: Type.String(),
  category: Type.String(),
  content: Type.String(),
  priority: Type.Number({ default: 0 }),
  autoGenerated: Type.Boolean({ default: false }),
  createdAt: Type.Number(),
  updatedAt: Type.Number(),
});

export type ProjectRule = Static<typeof ProjectRuleSchema>;

// ============================================================================
// 项目
// ============================================================================

export const ProjectSchema = Type.Object({
  id: Type.String(),
  name: Type.String(),
  description: Type.Optional(Type.String()),
  createdAt: Type.Number(),
  updatedAt: Type.Number(),
});

export type Project = Static<typeof ProjectSchema>;

// ============================================================================
// 会话
// ============================================================================

export const SessionSchema = Type.Object({
  id: Type.String(),
  projectId: Type.String(),
  title: Type.Optional(Type.String()),
  createdAt: Type.Number(),
  updatedAt: Type.Number(),
});

export type Session = Static<typeof SessionSchema>;

// ============================================================================
// 会话消息
// ============================================================================

export const SessionMessageSchema = Type.Object({
  id: Type.String(),
  sessionId: Type.String(),
  role: Type.String(),
  content: Type.String(),
  metadata: Type.Optional(Type.String()),
  createdAt: Type.Number(),
});

export type SessionMessage = Static<typeof SessionMessageSchema>;

// ============================================================================
// 记忆条目
// ============================================================================

export const MemoryEntrySchema = Type.Object({
  id: Type.String(),
  projectId: Type.String(),
  category: Type.String(),
  summary: Type.String(),
  sourceSessionId: Type.Optional(Type.String()),
  createdAt: Type.Number(),
});

export type MemoryEntry = Static<typeof MemoryEntrySchema>;

// ============================================================================
// 规则合并优先级
// ============================================================================

/**
 * 规则合并策略：
 * 1. 静态规则（code_style, constraints, domain_knowledge, best_practices）
 *    - 优先级：priority 字段决定
 *    - 来源：项目配置
 *
 * 2. 动态规则（completed_items, current_progress, decisions, blockers）
 *    - 优先级：动态生成，always high
 *    - 来源：会话状态
 *
 * 3. 记忆（session_summaries, key_learnings）
 *    - 优先级：medium
 *    - 来源：跨会话记忆
 */

export const RULE_PRIORITY = {
  static_low: 10,
  static_medium: 20,
  static_high: 30,
  memory: 50,
  dynamic_low: 70,
  dynamic_high: 80,
  critical: 90,
} as const;

export function getRulePriority(category: RuleCategory): number {
  const staticRules: RuleCategory[] = [
    'code_style', 'constraints', 'domain_knowledge', 'best_practices',
  ];
  const dynamicRules: RuleCategory[] = [
    'completed_items', 'current_progress', 'decisions', 'blockers',
  ];
  const memoryRules: RuleCategory[] = [
    'session_summaries', 'key_learnings',
  ];

  if (staticRules.includes(category)) return RULE_PRIORITY.static_medium;
  if (dynamicRules.includes(category)) return RULE_PRIORITY.dynamic_high;
  if (memoryRules.includes(category)) return RULE_PRIORITY.memory;
  return RULE_PRIORITY.static_low;
}
